# Generated by Django 2.1.7 on 2019-08-06 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('autor', models.CharField(max_length=60)),
                ('descipcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor_resena', models.CharField(blank=True, max_length=8, null=True)),
                ('resena', models.TextField(blank=True, null=True)),
                ('valoracion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resena', to='ebooks.Ebook')),
            ],
        ),
    ]
