# Generated by Django 2.1.7 on 2019-08-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=60)),
                ('email_empresa', models.EmailField(max_length=254)),
                ('titulo_trabajo', models.CharField(max_length=120)),
                ('descripcion_trabajo', models.TextField()),
                ('salario', models.IntegerField()),
                ('ciudad', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=60)),
            ],
        ),
    ]
