# Generated by Django 2.1.7 on 2019-08-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_de_trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertalaboral',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
