# Generated by Django 2.1.7 on 2019-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_de_trabajos', '0002_auto_20190806_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertalaboral',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
