# Generated by Django 2.1.7 on 2019-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_de_trabajos', '0003_auto_20190806_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('CLP', 'Peso Chileno'), ('EUR', 'Euro'), ('CNY', 'Yuan chino'), ('CAD', 'Dólar canadiense'), ('JPY', 'Yen'), ('GBP', 'Libra esterlina'), ('RUB', 'Rublo ruso')], default=None, max_length=3),
        ),
    ]
